Traceback:
File "/mount/src/iaagentes/app.py", line 7, in <module>
    from ultralytics import YOLO
File "/home/adminuser/venv/lib/python3.13/site-packages/ultralytics/__init__.py", line 11, in <module>
    from ultralytics.models import NAS, RTDETR, SAM, YOLO, YOLOE, FastSAM, YOLOWorld
File "/home/adminuser/venv/lib/python3.13/site-packages/ultralytics/models/__init__.py", line 3, in <module>
    from .fastsam import FastSAM
File "/home/adminuser/venv/lib/python3.13/site-packages/ultralytics/models/fastsam/__init__.py", line 3, in <module>
    from .model import FastSAM
File "/home/adminuser/venv/lib/python3.13/site-packages/ultralytics/models/fastsam/model.py", line 6, in <module>
    from ultralytics.engine.model import Model
File "/home/adminuser/venv/lib/python3.13/site-packages/ultralytics/engine/model.py", line 11, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
File "/home/adminuser/venv/lib/python3.13/site-packages/ultralytics/cfg/__init__.py", line 11, in <module>
    from ultralytics.utils import (
    ...<18 lines>...
    )
File "/home/adminuser/venv/lib/python3.13/site-packages/ultralytics/utils/__init__.py", line 22, in <module>
    import cv2
